name: Latest blog posts workflow
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in xiaojun.im posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.xiaojun.im/feed.xml"
          max_post_count: 5
